[package]
name = "my-cpu"
version = "0.1.0"
authors = ["Artyom Denezhny <denezhny@mer.govdnr.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.0"